#pragma once

#include <ntddk.h>

#ifndef RETOUCH_MAX_CONTACTS
#define RETOUCH_MAX_CONTACTS 10
#endif

#define RETOUCH_REPORT_ID_TOUCH       0x01
#define RETOUCH_REPORT_ID_MAX_COUNT   0x02
#define RETOUCH_REPORT_ID_CERT_BLOB   0x44

#define RETOUCH_FLAG_TIP_SWITCH 0x01

#pragma pack(push, 1)

typedef struct _RETOUCH_TOUCH_REPORT
{
    UCHAR ReportId;
    UCHAR Flags;
    UCHAR ContactId;
    USHORT X;
    USHORT Y;
    USHORT Width;
    USHORT Height;
    USHORT Azimuth;
    USHORT ScanTime;
    UCHAR ContactCount;

} RETOUCH_TOUCH_REPORT, * PRETOUCH_TOUCH_REPORT;

typedef struct _RETOUCH_MAX_COUNT_FEATURE_REPORT
{
    UCHAR ReportId;
    UCHAR MaximumContactCount;

} RETOUCH_MAX_COUNT_FEATURE_REPORT, * PRETOUCH_MAX_COUNT_FEATURE_REPORT;

typedef struct _RETOUCH_CERTIFICATION_BLOB_FEATURE_REPORT
{
    UCHAR ReportId;
    UCHAR Blob[256];

} RETOUCH_CERTIFICATION_BLOB_FEATURE_REPORT, * PRETOUCH_CERTIFICATION_BLOB_FEATURE_REPORT;

#pragma pack(pop)